name: Workflow 2 Build
on:
  repository_dispatch:
    types: [trigger-workflow-2]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:      
      COGNITO_USER_POOL_ID: "us-west-2_iq4sQovhE"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: debug1
      run: |
        echo "${{github.event_name}}"
        
    - name: Debug
      run: 
        echo ${{ env.BRANCH_NAME }}
        echo ${{ env.ENVIRONMENT }}
        echo ${{ github.event.client_payload.sha }}
 
